ci:
  skip: []

default_language_version:
  python: python3.12

repos:
  # general checks (see here: https://pre-commit.com/hooks.html)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict

  # ruff - linting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.1.5"
    hooks:
      - id: ruff
        name: ruff

  # mypy - lint-like type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
      - id: mypy
        entry: poetry run mypy --config-file pyproject.toml
        language: system
        pass_filenames: false

  # prettier - formatting JS, CSS, JSON, Markdown, ...
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        exclude: ^poetry.lock
